language: node_js

node_js:
  - node

script:
  - npm run build
  - npm run test

deploy:
  provider: npm
  email: benji7425@pm.me
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    branch: master
