steps:
  - label: ":crossed_fingers: Test"
    plugins:
      - docker#v3.3.0:
          image: "node:10"
          volumes: [".:/workdir"]
          workdir: "/workdir"
          mount-checkout: false
          command: ["/bin/bash", "-c", "npm ci --dev && npm run build-test"]
  - wait: ~
  - block: ":shipit: Ship?"
    prompt: "Publish to NPM?"
  - label: ":npm: Publish"
    plugins:
      - docker#v3.3.0:
          image: "node:10"
          volumes: [".:/workdir"]
          workdir: "/workdir"
          mount-checkout: false
          environment: ["NPM_AUTH_TOKEN"]
          command: ["/bin/bash", ".buildkite/scripts/publish.sh"]
  - label: ":github: Create release"
    plugins:
      - docker#v3.3.0:
          image: "benji7425/github-release-creator:latest"
          volumes: ["./CHANGELOG.md:/app/CHANGELOG.md"]
          mount-checkout: false
          environment: ["GITHUB_TOKEN"]
          command: ["--owner", "benji7425", "--repo", "disharmony", "--file", "CHANGELOG.md"]
    soft_fail: true